In [10]:
# Import numpy package and get alias as "np"
import numpy as np

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#1. Create a 1D array of numbers from 0 to 9.
x = np.arange(start=0,stop=10,step=1,dtype=int)
print(x)

In [12]:
#2. Create a 3×3 numpy array of all True’s
x = np.ones(shape=(3,3), dtype = bool)
print(x)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [79]:
#3. Given an array as input, print only odd numbers as output
inpt=np.array([1,2,3,4,5,6])
print(inpt[(inpt)%2==1])

[1 3 5]


In [80]:
#4. Replace all odd numbers in arr with -2
a = np.array([1,2,3,4,5,6])
print(np.where([(inpt)%2==1],-2,inpt))

[[-2  2 -2  4 -2  6]]


In [45]:
#5. How to reshape an array?
a1=np.array([[1,2],[3,4],[5,6]])
a2 = a.reshape((2,3))
print('Original Array :','\n',a1)
print('Original Shape :',a1.shape)

# Let's reshape the array X
print('Converted Array :','\n',a2)
print('Converted Shape : ',a2.shape)


Original Array : 
 [[1 2]
 [3 4]
 [5 6]]
Original Shape : (3, 2)
Converted Array : 
 [[1 2 3]
 [4 5 6]]
Converted Shape :  (2, 3)


In [64]:
#6. Convert a 1D array to a 2D array with 2 rows
A = np.array([1,2,3,4])
B = np.reshape(A, (-1,2))
print(B)

[[1 2]
 [3 4]]


In [92]:
#7. Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples. 
a =np.arange(1,10)
print(a[((a)%2==1)|((a)%4==0)])

[1 3 4 5 7 8 9]


In [114]:
#8. Given array, check if there are any null values and print them out. 
ar = np.array([1, 2, 3, 4, np.nan, 5, np.nan, 6, np.nan],dtype=float).reshape((3,3))
print(ar)

#Print boolean values
print(np.isnan(ar))

#Printing Indices
print(np.where(np.isnan(ar)))

[[ 1.  2.  3.]
 [ 4. nan  5.]
 [nan  6. nan]]
[[False False False]
 [False  True False]
 [ True False  True]]
(array([1, 2, 2]), array([1, 0, 2]))


In [119]:
#9. How to replace all missing values with 0 in a numpy array?
ar = np.array([1, 2, 3, 4, np.nan, 5, np.nan, 6, np.nan],dtype=float).reshape((3,3))
print(np.nan_to_num(ar))

[[1. 2. 3.]
 [4. 0. 5.]
 [0. 6. 0.]]


In [127]:
#10. How to find the count of each unique number in a NumPy array?
a = np.array( [1,2,2,2,3,3,4,5,6,7,8,8] )
print("Original array:",a)
print("Counts for each #:")
uniq_ele, count_ele = np.unique(a, return_counts=True)
print(np.asarray((uniq_ele, count_ele)))

Original array: [1 2 2 2 3 3 4 5 6 7 8 8]
Counts for each #:
[[1 2 3 4 5 6 7 8]
 [1 3 2 1 1 1 1 2]]


In [136]:
#11. How to convert a numeric to a categorical (text) array?
a1 = np.arange(25,dtype=int).reshape([5,5])
a2 = a1.astype(str)
print(a1.dtype)
print(a2.dtype)

int64
<U21


In [153]:
#12. Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both. 
a =np.arange(1,100)
np.setdiff1d(a[(((a)%5==0)|((a)%7==0))],b[(((b)%5==0)&((b)%7==0))])


array([ 5,  7, 10, 14, 15, 20, 21, 25, 28, 30, 40, 42, 45, 49, 50, 55, 56,
       60, 63, 65, 75, 77, 80, 84, 85, 90, 91, 95, 98])

In [158]:
#13. Write a program to reverse an array and print (Don’t use inbuilt reverse functions)
arr = np.arange(1,10)
print('Original Array:',arr)
print('Reversed Array:',arr[::-1])

Original Array: [1 2 3 4 5 6 7 8 9]
Reversed Array: [9 8 7 6 5 4 3 2 1]
